{"values":["Just Cause 2","PC","","Steam","","","AGENCY HOVERCRAFT<br>BLACK MARKET AERIAL PACK DLC<br>BLACK MARKET BOOM PACK DLC<br>BULL'S EYE RIFLE DLC<br>CAMO PARACHUTE DLC<br>CHAOD PARACHUTE DLC<br>CHEVALIER CLASSIC DLC<br>CHEVALIER ICE BREAKER DLC<br>DARE DEVIL PARACHUTE DLC<br>FIRESTORM PARACHUTE DLC<br>MONSTER TRUCK DLC<br>RICO'S SIGNATURE GUN DLC<br>SCORPION PARACHUTE DLC<br>TIGER PARACHUTE DLC<br>TUK TUK BOOM BOOM DLC<br>MULTIPLAYER MOD"],
"id":645,
"modif_id":3,
"image_size":[70,100],
"images":[],
"files":[]
}